In [148]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [149]:
data = pd.read_csv('Bengaluru_House_Data.csv')

In [150]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [151]:
data.sample()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
814,Built-up Area,Ready To Move,Hennur Road,2 BHK,NaN,1157,2.0,1.0,84.0

In [152]:
data.shape

(13320, 9)

In [153]:
data.info

<bound method DataFrame.info of                   area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II
1                Plot  Area  Ready To Move          Chikka Tirupathi
2            Built-up  Area  Ready To Move               Uttarahalli
3      Super built-up  Area  Ready To Move        Lingadheeranahalli
4      Super built-up  Area  Ready To Move                  Kothanur
...                     ...            ...                       ...
13315        Built-up  Area  Ready To Move                Whitefield
13316  Super built-up  Area  Ready To Move             Richards Town
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar
13318  Super built-up  Area         18-Jun           Padmanabhanagar
13319  Super built-up  Area  Ready To Move              Doddathoguru

            size  society total_sqft  bath  balcony   price
0          2 BHK  Coomee        1056   2.0      1.0   39.07
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00
2          3 BHK      NaN       1440   2.0      3.0   62.00
3          3 BHK  Soiewre       1521   3.0      1.0   95.00
4          2 BHK      NaN       1200   2.0      1.0   51.00
...          ...      ...        ...   ...      ...     ...
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00
13316      4 BHK      NaN       3600   5.0      NaN  400.00
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00
13319      1 BHK      NaN        550   1.0      1.0   17.00

[13320 rows x 9 columns]>

In [154]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
27 BHK           1
19 BHK           1
16 BHK           1
43 Bedroom       1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Maa 5a      1
AeisePV     1
SJovest     1
ThhtsV      1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
1020 - 1130      1
2758             1
1133 - 1384      1
774              1
4689             1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
14.0       1
27.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
96.80       1
63.93       1
40.14       1
231.00      1
488.00      1
Name: count, Length: 1994, dtype: int64
********************

Handling Missing Values

In [155]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [156]:
data.drop(columns=['area_type','availability','society','balcony'], inplace=True)

In [157]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [158]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  str
 1   size        13304 non-null  str
 2   total_sqft  13320 non-null  str
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), str(3)
memory usage: 520.4 KB

In [159]:
data['location'].value_counts()

location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64

In [160]:
data.isna().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [161]:
data['location'] = data['location'].fillna('Sarjapur  Road')

In [162]:
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
27 BHK           1
19 BHK           1
16 BHK           1
43 Bedroom       1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [163]:
data['size'] = data['size'].fillna('2 BHK')

In [164]:
data['bath'].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
14.0       1
27.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64

In [165]:
data['bath'] = data['bath'].fillna(data['bath'].median())

In [166]:
data.isna().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

Data Pre-Processing

In [167]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  str
 1   size        13320 non-null  str
 2   total_sqft  13320 non-null  str
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), str(3)
memory usage: 520.4 KB

In [168]:
data['bhk']=data['size'].str.split().str.get(0).astype(int)

In [169]:
data[data.bhk>10]

                            location        size total_sqft  bath  price  bhk
459                     1 Giri Nagar      11 BHK       5000   9.0  360.0   11
1718       2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
1768              1 Ramamurthy Nagar  11 Bedroom       1200  11.0  170.0   11
3379                  1Hanuman Nagar      19 BHK       2000  16.0  490.0   19
3609   Koramangala Industrial Layout      16 BHK      10000  16.0  550.0   16
3853               1 Annasandrapalya  11 Bedroom       1200   6.0  150.0   11
4684                     Munnekollal  43 Bedroom       2400  40.0  660.0   43
4916                   1Channasandra      14 BHK       1250  15.0  125.0   14
6533                     Mysore Road  12 Bedroom       2232   6.0  300.0   12
7979                   1 Immadihalli      11 BHK       6000  12.0  150.0   11
9935                   1Hoysalanagar      13 BHK       5425  13.0  275.0   13
11559                  1Kasavanhalli  18 Bedroom       1200  18.0  200.0   18

In [170]:
data[data.bhk>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [171]:
data['total_sqft'].value_counts()

total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
1020 - 1130      1
2758             1
1133 - 1384      1
774              1
4689             1
Name: count, Length: 2117, dtype: int64

In [172]:
data['total_sqft'].unique()

<StringArray>
[       '1056',        '2600',        '1440',        '1521',        '1200',
        '1170',        '2732',        '3300',        '1310',        '1020',
 ...
        '3124',        '9200',         '613',         '250',        '2395',
 '1020 - 1130',        '2758', '1133 - 1384',         '774',        '4689']
Length: 2117, dtype: str

In [173]:
def convertRange(x):
    temp = x.split('-')
    if len(temp) == 2:
        return (float(temp[0])+float(temp[1]))/2
    try: 
        return float(x)
    except:
        return None

In [174]:
data['total_sqft']=data['total_sqft'].apply(convertRange)

In [175]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [176]:
data['price-per-sqft']=data['price']*100000/data['total_sqft']

In [177]:
data.sample(10)

,location,size,total_sqft,bath,price,bhk,price-per-sqft
6213,Hulimavu,3 BHK,3035.0,5.0,220.00,3,7248.764415
10126,Kudlu,2 BHK,1300.0,2.0,56.00,2,4307.692308
8992,Queens Road,3 BHK,1405.0,3.0,169.00,3,12028.469751
12791,Bannerghatta Road,2 BHK,1122.5,2.0,61.74,2,5500.222717
4703,Vittasandra,2 BHK,1404.0,2.0,68.80,2,4900.284900
12153,Kothanur,3 BHK,1581.0,3.0,76.00,3,4807.084124
5375,Hosur Road,2 BHK,950.0,2.0,60.00,2,6315.789474
570,Whitefield,4 Bedroom,4144.0,4.0,315.00,4,7601.351351
4168,Hosur Road,1 BHK,760.0,1.0,21.28,1,2800.000000
7826,Balaji Gardens Layout,1 BHK,825.0,2.0,40.00,1,4848.484848

In [178]:
data.describe()

         total_sqft          bath         price           bhk  price-per-sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [179]:
data['location'].value_counts()

location
Whitefield                                         540
Sarjapur  Road                                     400
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64

In [180]:
data['location'] = data['location'].apply(lambda x: x.strip())

In [181]:
location_count =data['location'].value_counts()

In [182]:
location_count

location
Whitefield                                         541
Sarjapur  Road                                     400
Electronic City                                    304
Kanakpura Road                                     273
Thanisandra                                        237
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1294, dtype: int64

In [183]:
location_count_less_than_10 = location_count[location_count<=10]
location_count_less_than_10

location
Ganga Nagar                                        10
Dairy Circle                                       10
Sadashiva Nagar                                    10
Naganathapura                                      10
Nagappa Reddy Layout                               10
                                                   ..
Pattegarhpalya                                      1
Tilak Nagar                                         1
12th cross srinivas nagar banshankari 3rd stage     1
Havanur extension                                   1
Abshot Layout                                       1
Name: count, Length: 1053, dtype: int64

In [184]:
data['location']=data['location'].apply(lambda x : 'other' if x in location_count_less_than_10 else x)

Outlier detection and handling

In [185]:
data.describe()

         total_sqft          bath         price           bhk  price-per-sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [186]:
(data['total_sqft']/data['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [187]:
data = data[((data['total_sqft']/data['bhk']) >= 300)]
data.describe()

         total_sqft          bath         price           bhk  price-per-sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [188]:
data.shape

(12530, 7)

In [189]:
data['price-per-sqft'].describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price-per-sqft, dtype: float64

In [ ]:
def remove_outliers_sqft(df):
    df_output = pd.DataFrame()
    for key,subdf in df.groupby('location'):
        m = np.mean(subdf['price-per-sqft'])
        st = np.std(subdf['price-per-sqft'])
        gen_df = subdf[(subdf['price-per-sqft'] > (m-st)) &  (subdf['price-per-sqft'] <= (m+st))]
        df_output = pd.concat([df_output,gen_df], ignore_index=True)
    return df_output
data = remove_outliers_sqft(data)
data.describe()

NameError: name 'subbdf' is not defined